name: CI
on:
  pull_request:
jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.5"
          cache: true
          cache-dependency-path: server/go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          working-directory: server
      - name: generate swagger
        run: |
          cd server
          go install github.com/swaggo/swag/v2/cmd/swag@v2.0.0-rc4
          go generate ./...
      - name: build
        run: |
          cd server
          go build -o messenger-backend cmd/main.go
